spring:
  application:
    name: zuul-service

zuul:
  routes:
    data-access-service:
      path: /data-access-service/**
      url: http://localhost:8081/
    weather-service:
      path: /weather-service/**
      url: http://localhost:8082/

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    instance: hostname